apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::110982594518:role/smartretailx-eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::110982594518:user/SmartRetailX
      username: SmartRetailX
      groups:
      - system:masters
    - userarn: arn:aws:iam::110982594518:root
      username: root
      groups:
      - system:masters
